# Generated by Django 4.2.17 on 2026-05-19 16:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('role', models.CharField(choices=[('user', '一般會員'), ('admin', '管理員')], default='user', max_length=20)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('initial_weight', models.FloatField(blank=True, null=True)),
                ('activity_level', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(default='份', max_length=50)),
                ('calories', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('approved', '已核准'), ('pending', '待審核'), ('rejected', '已拒絕'), ('user_created', '使用者新增')], default='approved', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to='my_backend.members')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemberAchievements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_achievements', to='my_backend.achievements')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_achievements', to='my_backend.members')),
            ],
            options={
                'db_table': 'member_achievements',
            },
        ),
        migrations.CreateModel(
            name='DietRecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐')], max_length=20)),
                ('serving_size', models.FloatField(default=1)),
                ('food_name', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('calories', models.FloatField(default=0)),
                ('total_calories', models.FloatField(default=0)),
                ('log_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_records', to='my_backend.members')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_records', to='my_backend.products')),
            ],
            options={
                'db_table': 'diet_records',
                'ordering': ['-log_date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='DailyLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='my_backend.members')),
            ],
            options={
                'db_table': 'daily_logs',
                'ordering': ['-date'],
            },
        ),
    ]
