# Generated by Django 5.2.14 on 2026-05-19 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=5, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('initial_weight', models.FloatField(blank=True, null=True)),
                ('activity_level', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='MemberAchievements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_backend.achievements')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_backend.members')),
            ],
            options={
                'db_table': 'member_achievements',
            },
        ),
        migrations.CreateModel(
            name='DailyLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_backend.members')),
            ],
            options={
                'db_table': 'daily_logs',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_backend.members')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='DietRecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_type', models.CharField(blank=True, max_length=9, null=True)),
                ('serving_size', models.FloatField(blank=True, null=True)),
                ('log_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_backend.members')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_backend.products')),
            ],
            options={
                'db_table': 'diet_records',
            },
        ),
    ]
