# Generated by Django 4.2.17 on 2026-05-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='members',
            name='name',
        ),
    ]
