# Generated by Django 4.2.30 on 2026-05-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_backend', '0002_remove_members_avatar_remove_members_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
